.Dd $Mdocdate$
.Dt ehcpi.conf 5
.Os
.Sh NAME
.Nm ehcpi.conf
.Nd ehcpi configuration file
.Sh DESCRIPTION
This manual describes the
.Xr ehcpi 8
configuration file.
\n
Lines containing a single newline are accepted, no other stylistic features (comments, etc) are supported.
\n
The following options are accepted:
.Bl -tag -width Ds
.It Ic event Ar do Ar action
Registers an input event and an action (a command) to perform in response.
.Sh FILES
.Pa /etc/ehcpi.conf
configuration file
.Sh SEE ALSO
.Xr ehcpi 8
